# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{adept_geoip}
  s.version = "1.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Craig Heneveld}]
  s.date = %q{2012-02-21}
  s.description = %q{GeoIP searches a GeoIP database for a given host or IP address, and
returns information about the country where the IP address is allocated,
and the city, ISP and other information, if you have that database version. Forked by Adept Mobile to modify/extend.}
  s.email = [%q{craig.heneveld@adeptmobi.com}]
  s.executables = [%q{geoip}]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "History.rdoc",
    "README.rdoc",
    "Rakefile",
    "bin/geoip",
    "config/website.yml",
    "data/geoip/country_code.yml",
    "data/geoip/country_code3.yml",
    "data/geoip/country_continent.yml",
    "data/geoip/country_name.yml",
    "data/geoip/time_zone.yml",
    "geoip.gemspec",
    "lib/geoip.rb",
    "script/destroy",
    "script/generate",
    "script/txt2html",
    "test/test_geoip.rb",
    "test/test_helper.rb",
    "website/index.txt",
    "website/javascripts/rounded_corners_lite.inc.js",
    "website/stylesheets/screen.css",
    "website/template.rhtml"
  ]
  s.homepage = %q{https://github.com/AdeptMobile/geoip}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.8}
  s.summary = %q{GeoIP searches a GeoIP database for a given host or IP address, and returns information about the country where the IP address is allocated, and the city, ISP and other information, if you have that database version.Forked by Adept Mobile to modify/extend.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

